name: Site build
# workflow triggers
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [build]

# build process
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency: 
      group: main
      cancel-in-progress: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: building
      env:
          VIMEO_ACCESS_TOKEN: ${{ secrets.VIMEO_ACCESS_TOKEN }}
          VIMEO_CLIENT_ID: ${{ secrets.VIMEO_CLIENT_ID }}
          VIMEO_CLIENT_SECRET: ${{ secrets.VIMEO_CLIENT_SECRET }}
          VIMEO_CLIENT_PATH: ${{ secrets.VIMEO_CLIENT_PATH }}
      run: |
          npm ci
          npm run build
        
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.FTP_URI }} 
        username: ${{ secrets.DEV_USER_ID }}
        password: ${{ secrets.DEV_FTP_PASSWORD }}
        local-dir: ./public/
        server-dir : dev/
